spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/db/jspringjpa
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto : create
    properties:
      hibernate:
    # show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace
decorator:
  datasource:
    enabled: true
    datasource-proxy:
      multiline: true
    p6spy:
      logging: slf4j
